/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CmButton: typeof import('./CmButton/index.vue')['default']
    CmDialog: typeof import('./CmDialog/index.vue')['default']
    CmInput: typeof import('./CmInput/index.vue')['default']
    CmSelect: typeof import('./CmSelect/index.vue')['default']
    CmSvg: typeof import('./CmSvg/index.vue')['default']
    CmTable: typeof import('./CmTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    IconCarbon4kFilled: typeof import('~icons/carbon/4k-filled')['default']
    IconClarityCancelLine: typeof import('~icons/clarity/cancel-line')['default']
    IconLineMdCancel: typeof import('~icons/line-md/cancel')['default']
    IconLineMdConfirmCircle: typeof import('~icons/line-md/confirm-circle')['default']
    IconMdiLightCancel: typeof import('~icons/mdi-light/cancel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./test.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
